CREATE DATABASE KhoaHoc
GO 
USE KhoaHoc
GO
CREATE TABLE NhanVien(
	MaNV NVARCHAR(20) NOT NULL PRIMARY KEY,
	MatKhau NVARCHAR(50) NOT NULL,
	HoTen NVARCHAR(50) NOT NULL,
	VaiTro BIT DEFAULT 0
	)
CREATE TABLE ChuyenDe(
	MaCD VARCHAR(20) NOT NULL PRIMARY KEY,
	TenCD NVARCHAR(50) NOT NULL,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	Hinh NVARCHAR(50) NOT NULL,
	Mota NVARCHAR(225) NOT NULL,
)
CREATE TABLE KhoaHoc(
	MaKH INT IDENTITY(1,1) PRIMARY KEY,
	MaCD VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES ChuyenDe(MaCD),
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	NgayKG DATE NOT NULL,
	GhiChu NVARCHAR(225) NULL,
	MaNV NVARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NhanVien(MaNV),
	NgayTao DATE DEFAULT getDATE()
)
CREATE TABLE NguoiHoc(
	MaNH VARCHAR(20) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	GioiTinh BIT DEFAULT 1,
	DienThoai NVARCHAR(24) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	GhiChu NVARCHAR(225) NULL,
	MaNV NVARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NhanVien(MaNV),
	NgayDK DATE DEFAULT getdate()
)
CREATE TABLE HocVien(
	MaHV INT IDENTITY(1,1) PRIMARY KEY,
	MaKH INT NOT NULL FOREIGN KEY REFERENCES KhoaHoc(MaKH),
	MaNH VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NguoiHoc(MaNH),
	Diem FLOAT DEFAULT -1
)